### ISSUE TITLE
Connect authentication

### ISSUE THREAD

**Issue by saro0h** [poledev/adrien#21]
- [ ] https://gist.github.com/saro0h/85fbe815c50e4d501c8e (in french)

- [ ]Create an application on connect :

     - Redirect URI : http://jobs.vserver-yourname.dev.sensio.net/app_dev.php/session/callback

     - Information to seize in config/parameters.yml : 
          sensiolabs_connect.app_id:         Id
         sensiolabs_connect.app_secret:   Secret
         sensiolabs_connect.scope:           'SCOPE_EMAIL SCOPE_LOCATION SCOPE_PUBLIC’

--------------------------

![capture decran 2014-01-03 a 11 00 06](https://f.cloud.github.com/assets/667519/1896202/ee85223a-7b88-11e3-89cd-2748851911fb.png)

--------------------------

- Authorize yourself as administrator : 
    Add your username in the app/config/security.yml file

```
providers:
    sensiolabs_connect:
        connect_memory:
            users:
                36221b12-f362-4dca-8724-4da82ef2ba49: "ROLE_ADMIN"
```

![capture decran 2014-01-03 a 11 27 58](https://f.cloud.github.com/assets/667519/1896205/1aeb6e06-7b89-11e3-89cf-af568c9b4680.png)
